#!/usr/bin/env node
// extract-icons.js
// Extracts all primary SVG icons from a local aegis-icons repo clone
// into frontend/public/icons/ with lowercase kebab-case filenames.
// Also auto-generates internal/iconmatch/slugs.go and frontend/src/data/iconSlugs.ts
// from the extracted filenames, and syncs aliases.json between internal/ and frontend/.
//
// Usage: node scripts/extract-icons.js /path/to/aegis-icons
//
// Clone the repo first:
//   git clone --depth 1 https://github.com/aegis-icons/aegis-icons.git /tmp/aegis-icons
//
// Note: pack.json checked — issuer arrays contain only [name], no additional aliases.

const fs = require("fs");
const path = require("path");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function toSlug(name) {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function findSvgDir(repoPath) {
  // Prefer icons/1_Primary/ (contains all primary icons)
  const primary = path.join(repoPath, "icons", "1_Primary");
  if (fs.existsSync(primary)) return primary;

  // Fall back to SVG/ only if primary dir doesn't exist
  const fallback = path.join(repoPath, "SVG");
  if (fs.existsSync(fallback)) return fallback;

  return null;
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------
function writeGoSlugs(slugs, outputPath) {
  const lines = [
    "// Code generated by scripts/extract-icons.js; DO NOT EDIT.",
    "",
    "package iconmatch",
    "",
    "// Slugs contains all valid icon slugs, sorted alphabetically.",
    "// Each slug corresponds to a .svg file in frontend/public/icons/.",
    "var Slugs = []string{",
  ];
  for (const slug of slugs) {
    lines.push(`\t${JSON.stringify(slug)},`);
  }
  lines.push("}");
  fs.writeFileSync(outputPath, lines.join("\n") + "\n");
}

function writeTSSlugs(slugs, outputPath) {
  const lines = [
    "// Code generated by scripts/extract-icons.js; DO NOT EDIT.",
    "",
    "// Icon slugs — generated from SVG filenames in frontend/public/icons/.",
    "// Each slug corresponds to /icons/{slug}.svg in the bundled assets.",
    "export const ICON_SLUGS: readonly string[] = [",
  ];
  for (const slug of slugs) {
    lines.push(`  ${JSON.stringify(slug)},`);
  }
  lines.push("] as const;");
  fs.writeFileSync(outputPath, lines.join("\n") + "\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
function main() {
  const repoPath = process.argv[2];

  if (!repoPath || !fs.existsSync(repoPath)) {
    console.error(
      "Usage: node scripts/extract-icons.js /path/to/aegis-icons\n"
    );
    console.error("Clone the repo first:");
    console.error(
      "  git clone --depth 1 https://github.com/aegis-icons/aegis-icons.git /tmp/aegis-icons"
    );
    process.exit(1);
  }

  const svgDir = findSvgDir(repoPath);
  if (!svgDir) {
    console.error(
      `Error: Cannot find SVG directory in ${repoPath}. Expected icons/1_Primary/ or SVG/.`
    );
    process.exit(1);
  }

  console.log(`SVG source directory: ${svgDir}`);

  // Destination directory for copied SVGs
  const destDir = path.resolve(__dirname, "..", "frontend", "public", "icons");
  fs.mkdirSync(destDir, { recursive: true });

  // Walk source directory and copy all SVGs (skip "outdated" dirs)
  const seenSlugs = new Map(); // slug -> source path (first wins on collision)
  const copiedSlugs = [];

  function walkDir(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        // Skip directories whose name (case-insensitive) contains "outdated"
        if (entry.name.toLowerCase().includes("outdated")) {
          console.log(`  Skipping outdated dir: ${fullPath}`);
          continue;
        }
        walkDir(fullPath);
      } else if (
        entry.isFile() &&
        entry.name.toLowerCase().endsWith(".svg")
      ) {
        const baseName = path.basename(entry.name, ".svg");
        const slug = toSlug(baseName);

        if (seenSlugs.has(slug)) {
          // First wins — log collision warning and skip
          console.warn(
            `  WARN: slug collision "${slug}" — keeping ${seenSlugs.get(slug)}, skipping ${fullPath}`
          );
          continue;
        }

        seenSlugs.set(slug, fullPath);
        const destPath = path.join(destDir, `${slug}.svg`);
        fs.copyFileSync(fullPath, destPath);
        copiedSlugs.push(slug);
      }
    }
  }

  walkDir(svgDir);

  // Sort slugs alphabetically
  copiedSlugs.sort();

  console.log(`\nCopied ${copiedSlugs.length} icons to ${destDir}`);

  // Generate slugs.go
  const goSlugsPath = path.resolve(
    __dirname,
    "..",
    "internal",
    "iconmatch",
    "slugs.go"
  );
  writeGoSlugs(copiedSlugs, goSlugsPath);
  console.log(`Generated: ${goSlugsPath} (${copiedSlugs.length} slugs)`);

  // Generate iconSlugs.ts
  const tsSlugsPath = path.resolve(
    __dirname,
    "..",
    "frontend",
    "src",
    "data",
    "iconSlugs.ts"
  );
  writeTSSlugs(copiedSlugs, tsSlugsPath);
  console.log(`Generated: ${tsSlugsPath} (${copiedSlugs.length} slugs)`);

  // Sync aliases.json from internal/ to frontend/public/icons/
  const srcAliases = path.resolve(
    __dirname,
    "..",
    "internal",
    "iconmatch",
    "aliases.json"
  );
  const destAliases = path.join(destDir, "aliases.json");
  fs.copyFileSync(srcAliases, destAliases);
  const aliasCount = Object.keys(JSON.parse(fs.readFileSync(srcAliases, "utf8"))).length;
  console.log(`Synced aliases.json to frontend/public/icons/ (${aliasCount} entries)`);

  // Summary
  console.log("\n--- Summary ---");
  console.log(`Copied: ${copiedSlugs.length} icons`);
  console.log(
    `Generated: internal/iconmatch/slugs.go (${copiedSlugs.length} slugs)`
  );
  console.log(
    `Generated: frontend/src/data/iconSlugs.ts (${copiedSlugs.length} slugs)`
  );
  console.log(`Synced: aliases.json (${aliasCount} entries)`);
}

main();
