// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {entries} from '../models';
import {vaultctrl} from '../models';
import {importer} from '../models';

export function AddEntry(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number,arg9:string,arg10:string,arg11:boolean):Promise<void>;

export function ChangeVaultPassword(arg1:string,arg2:string):Promise<void>;

export function CopyCode(arg1:string):Promise<void>;

export function CreateGroup(arg1:string,arg2:string):Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function ExportNow():Promise<string>;

export function GetBackupSettings():Promise<main.BackupSettings>;

export function GetCodes():Promise<Array<entries.CodePayload>>;

export function GetEntries():Promise<Array<entries.EntryMetadata>>;

export function GetEntryDetails(arg1:string):Promise<entries.EntryDetails>;

export function GetEntryGroups():Promise<Array<entries.GroupInfo>>;

export function GetIconSuggestion(arg1:string):Promise<string>;

export function GetSetting(arg1:string):Promise<string>;

export function GetVaultStatus():Promise<vaultctrl.VaultStatus>;

export function ImportFile(arg1:string,arg2:string):Promise<importer.ImportResult>;

export function LockVault():Promise<void>;

export function ParseAndPreviewURI(arg1:string):Promise<main.URIPreview>;

export function PickAndScanQRFile():Promise<main.URIPreview>;

export function PickBackupDir():Promise<string>;

export function PickFile():Promise<string>;

export function RemovePassword(arg1:string):Promise<void>;

export function RenameGroup(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderGroups(arg1:Array<string>):Promise<void>;

export function ScanQRFile(arg1:string):Promise<main.URIPreview>;

export function ScanQRScreen():Promise<main.URIPreview>;

export function SetBackupSettings(arg1:string,arg2:string):Promise<void>;

export function SetPassword(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UndoDelete():Promise<void>;

export function UnlockVault(arg1:string):Promise<void>;

export function UpdateEntry(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:number,arg9:number,arg10:string,arg11:string):Promise<void>;
