// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntry(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['AddEntry'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function ChangeVaultPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeVaultPassword'](arg1, arg2);
}

export function CopyCode(arg1) {
  return window['go']['main']['App']['CopyCode'](arg1);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function ExportNow() {
  return window['go']['main']['App']['ExportNow']();
}

export function GetBackupSettings() {
  return window['go']['main']['App']['GetBackupSettings']();
}

export function GetCodes() {
  return window['go']['main']['App']['GetCodes']();
}

export function GetEntries() {
  return window['go']['main']['App']['GetEntries']();
}

export function GetEntryDetails(arg1) {
  return window['go']['main']['App']['GetEntryDetails'](arg1);
}

export function GetEntryGroups() {
  return window['go']['main']['App']['GetEntryGroups']();
}

export function GetIconSuggestion(arg1) {
  return window['go']['main']['App']['GetIconSuggestion'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetVaultStatus() {
  return window['go']['main']['App']['GetVaultStatus']();
}

export function ImportFile(arg1, arg2) {
  return window['go']['main']['App']['ImportFile'](arg1, arg2);
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function ParseAndPreviewURI(arg1) {
  return window['go']['main']['App']['ParseAndPreviewURI'](arg1);
}

export function PickAndScanQRFile() {
  return window['go']['main']['App']['PickAndScanQRFile']();
}

export function PickBackupDir() {
  return window['go']['main']['App']['PickBackupDir']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function RemovePassword(arg1) {
  return window['go']['main']['App']['RemovePassword'](arg1);
}

export function RenameGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2, arg3);
}

export function ReorderGroups(arg1) {
  return window['go']['main']['App']['ReorderGroups'](arg1);
}

export function ScanQRFile(arg1) {
  return window['go']['main']['App']['ScanQRFile'](arg1);
}

export function ScanQRScreen() {
  return window['go']['main']['App']['ScanQRScreen']();
}

export function SetBackupSettings(arg1, arg2) {
  return window['go']['main']['App']['SetBackupSettings'](arg1, arg2);
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function UndoDelete() {
  return window['go']['main']['App']['UndoDelete']();
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function UpdateEntry(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['UpdateEntry'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}
